# docker-compose -f docker-compose.kafka.yml up --build -d
# https://github.com/simplesteph/kafka-stack-docker-compose/blob/master/zk-single-kafka-single.yml

version: "3.4"

services:
    zookeeper:
        image: wurstmeister/zookeeper
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        hostname: kafka
        container_name: kafka
        ports:
            - "9092:9092"
            - "9094:9094"
        links:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_CREATE_TOPICS: "mytopic:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            HOSTNAME_COMMAND: "echo 127.0.0.1"
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
        volumes:
            - ./.docker/kafka/run/docker.sock:/var/run/docker.sock

    sample-kafka-producer:
        build:
            context: .
            dockerfile: ./src/Samples/Sample.Kafka.Producer/Dockerfile
        container_name: Sample.Kafka.Producer
        volumes:
            - ./.docker/kafka/Sample.Kafka.Producer/Logs/:/app/Logs/
        environment:
            KAFKA_BOOTSTRAP_SERVERS: kafka:9092
            KAFKA_TOPIC: product-topic
        links: 
            - kafka

    sample-kafka-consumer:
        build:
            context: .
            dockerfile: ./src/Samples/Sample.Kafka.Consumer/Dockerfile
        container_name: Sample.Kafka.Consumer
        volumes:
            - ./.docker/kafka/Sample.Kafka.Consumer/Logs/:/app/Logs/
        environment:
            KAFKA_BOOTSTRAP_SERVERS: kafka:9092
            KAFKA_TOPIC: product-topic
            KAFKA_GROUP_ID: product-group-id
        links: 
            - kafka
